import Head from 'next/head'
import {Form, Formio} from '@formio/react'
import styles from '../styles/Home.module.css'

Formio.template = 'tailwind';
Formio.use(tailwind);

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>100 Blocks a Day</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <h1 className={styles.heading}>100 Blocks a Day</h1>

            <div className={styles.console}>
                <div className={styles.grid}>
                    {
                        [...Array(100)].map((_, i) => (
                            <div className={styles.box} key={i}/>
                        ))

                    }
                </div>

                <div className={styles.form}>
                    <Form form={{
                        "components": [
                            {
                                "label": "Text Field",
                                "tableView": true,
                                "key": "textField",
                                "type": "textfield",
                                "input": true
                            },
                            {
                                "type": "button",
                                "label": "Submit",
                                "key": "submit",
                                "disableOnInvalid": true,
                                "input": true,
                                "tableView": false
                            }
                        ]
                    }}/>
                </div>
            </div>
    </div>
  )
}
